---
title: "Examples"
format: pdf
editor: visual
---

## Examples R package

Install R Package

```{r}
setwd("C:/Users/mbofi/Dropbox/CeMSIIS/GitHub/ewhorm_sim/rpkg")
# install.packages('C:/Users/mbofi/Dropbox/CeMSIIS/GitHub/ewhorm_sim/ewhorm_0.1.tar.gz',repos=NULL)
library(ewhorm)
```

## Simulate data

```{r}
simulated_data <- ewhorm::sim_data(n_arms = 4,
                                   N = 30 * 4,
                                   mu_6m = c(0,0,0,0),
                                   mu_12m= c(0,0,0,0),
                                   sigma=diag(1,2),
                                   rmonth =12)
head(simulated_data,10)
```



## Simulate trial 

```{r}
result_trial <- sim_trial(n_arms=4, 
                          N1=120, N2=60, 
                          mu_6m = c(0,0,0,0),
                          mu_12m= c(0,0,0,0), 
                          sigma=diag(1,2), 
                          rmonth=12, 
                          alpha1=0.5, 
                          alpha=0.05, 
                          p_safety=c(0.9,0.8,0.7), 
                          safety=T)

(result_trial)
```

